kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: {{ .Values.ceph.mon }}
  adminId: admin
  adminSecretName: ceph-admin-secret-{{ .Release.Name }}
  adminSecretNamespace: kube-system